#!/usr/bin/ruby
# CODING: utf-8
require 'date'

dn = %W(日 月 火 水 木 金 土)

d = Date.today
puts "本日 " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

d = Date.today+1
puts "明日 " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

d = Date.today+2
puts "     " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

d = Date.today+3
puts "     " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

d = Date.today+4
puts "     " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

d = Date.today+5
puts "     " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

d = Date.today+6
puts "     " + d.strftime("%m月%d日") + "(" + dn[d.wday] + ")" + "  / " + d.strftime("%B %d (%A)")

# 課題: 記述方法の洗練、関数の利用

